name: Publish to Registry
on: [push, pull_request]

jobs:
  generate_output:
    runs-on: ubuntu-latest
    outputs:
      package_version: ${{ steps.output.outputs.package_version }}
      current_version_json: ${{ steps.output.outputs.current_version_json }}
    steps:
      - uses: actions/checkout@v2
      - name: Get current package version
        run: package_version=$(cat package.json| jq -r .version) >> $GITHUB_ENV
      - name: Check if target version has been already published
        run: |
          export current_version_json=curl https://api.github.com/users/kyujin-cho/packages/npm/websocket-tunnel/versions \
            -H "Authorization: token ${{ secrets.PACKAGE_SECRET }}" | \
            jq -c ".[] | select( .name == $(cat package.json| jq .version) )" >> $GITHUB_ENV
      - name: Store output
        id: output
        run: |
          echo "::set-output name=package_version::${{ env.package_version }}"
          echo "::set-output name=current_version_json::${{ env.current_version_json }}"
  'NPM Package':
    runs-on: ubuntu-latest
    needs: generate_output
    if: ${{ !needs.generate_output.outputs.current_version_json }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js 14
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
      - name: Inject custom .npmjs file
        run: |
          echo "@kyujin-cho:registry=https://npm.pkg.github.com/" > /home/runner/.npmrc
          echo "//npm.pkg.github.com/:_authToken=$NODE_AUTH_TOKEN" >> /home/runner/.npmrc
          cat /home/runner/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PACKAGE_SECRET }}
      - name: Install dependencies
        run: |
          yarn install
        env:
          NPM_CONFIG_USERCONFIG: /home/runner/.npmrc
      - name: Publish package
        run: |
          npm publish
        env:
          NPM_CONFIG_USERCONFIG: /home/runner/.npmrc
  'Docker Registry':
    runs-on: ubuntu-latest
    needs: generate_output
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js 14
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
      - name: Install dependencies
        run: |
          npm i -g yarn
          yarn install
      - name: Compile TypeScript
        run: |
          yarn tsc
      - name: Determine Docker image name
        run: |
          echo image_name=ghcr.io/kyujin-cho/websocket-tunnel >> $GITHUB_ENV
      - name: Build Docker image
        run: docker build -t ${{ env.image_name }}:${{ needs.generate_output.outputs.image_version }} -t ${{ env.image_name }}:latest .
      - name: Publish image
        run: |
          echo ${{ secrets.PACKAGE_SECRET }} | docker login ghcr.io --username kyujin-cho --password-stdin
          docker push ${{ env.image_name }} --all-tags
